version: '3'
services:
  
  db:
    build: ./db
    restart: always
    volumes:
      - db:/var/lib/postgresql/data

  queue:
    build: ./queue
    restart: always
    volumes:
      - queue:/var/lib/rabbitmq

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80

volumes:
  db:
  queue:
