version: '3'
services:
  
  db:
    build: ./db
    restart: always
    volumes:
      - db:/var/lib/postgresql/data

  queue:
    build: ./queue
    restart: always
    volumes:
      - queue:/var/lib/rabbitmq

volumes:
  db:
  queue:
